1640WebApp/Controllers/NotificationUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _1640WebApp.Data;
using _1640WebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace _1640WebApp.Controllers
{
    [Authorize(Roles = "Staff, Admin, Manager, Coordinator")]
    public class NotificationUserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NotificationUserController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: NotificationUser
        public async Task<IActionResult> Index()
        {
            var notifications = await _context.tNotifications.OrderByDescending(n => n.Id).ToListAsync();
            var types = await _context.tNotifications.Select(n => n.Type).Distinct().ToListAsync();
            var allOptions = new List<SelectListItem>();
            allOptions.Add(new SelectListItem { Text = " -- Select --", Value = "" });
            foreach (var type in types)
            {
                allOptions.Add(new SelectListItem { Text = type, Value = type });
            }
            ViewBag.Types = allOptions;
            return View(notifications);
        }
        // sort
        public async Task<IActionResult> Filter(string typeData)
        {
            var notifications = await _context.tNotifications.OrderByDescending(n => n.Id).ToListAsync();

            // select data (Type) in database 
            // sau này lấy thêm datetime (đã note)
            var types = await _context.tNotifications.Select(n => n.Type).Distinct().ToListAsync();
            //var latestDay = _context.Notifications.Max(n => n.Day);
            //var earliestDay = _context.Notifications.Min(n => n.Day);
            var allOptions = new List<SelectListItem>();
            allOptions.Add(new SelectListItem { Text = " -- Select --", Value = "" });
            foreach (var type in types)
            {
                allOptions.Add(new SelectListItem { Text = type, Value = type });
            }
            //allOptions.Add(new SelectListItem { Text = $"Latest day: {latestDay.ToShortDateString()}", Value = latestDay.ToString("yyyy-MM-dd") });
            //allOptions.Add(new SelectListItem { Text = $"Earliest day: {earliestDay.ToShortDateString()}", Value = earliestDay.ToString("yyyy-MM-dd") });
            ViewBag.Types = allOptions;

            if (!String.IsNullOrEmpty(typeData))
            {
                //notifications = await notifications.Where(n => n.Type == typeData).ToListAsync();
                notifications = await _context.tNotifications
                    .Where(n => n.Type == typeData)
                    .OrderByDescending(n => n.Id)
                    .ToListAsync();
            }

            //return RedirectToAction("Index", notifications);
            return View("Index", notifications);
        }
        // handle search
        public async Task<IActionResult> Search(string searchString)
        {
            // select data (Type) in database 
            // sau này lấy thêm datetime (đã note)
            var types = await _context.tNotifications.Select(n => n.Type).Distinct().ToListAsync();
            //var latestDay = _context.Notifications.Max(n => n.Day);
            //var earliestDay = _context.Notifications.Min(n => n.Day);
            var allOptions = new List<SelectListItem>();
            allOptions.Add(new SelectListItem { Text = " -- Select --", Value = "" });
            foreach (var type in types)
            {
                allOptions.Add(new SelectListItem { Text = type, Value = type });
            }
            //allOptions.Add(new SelectListItem { Text = $"Latest day: {latestDay.ToShortDateString()}", Value = latestDay.ToString("yyyy-MM-dd") });
            //allOptions.Add(new SelectListItem { Text = $"Earliest day: {earliestDay.ToShortDateString()}", Value = earliestDay.ToString("yyyy-MM-dd") });
            ViewBag.Types = allOptions;

            // data after search
            var results = await _context.tNotifications
                .Where(n => n.Title.Contains(searchString) ||
                            n.Content.Contains(searchString))
                .OrderByDescending(n => n.Id)
                .ToListAsync();

            return View("Index", results);
        }

        // GET: NotificationUser/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.tNotifications == null)
            {
                return NotFound();
            }

            var tNotification = await _context.tNotifications
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tNotification == null)
            {
                return NotFound();
            }

            return View(tNotification);
        }

        // GET: NotificationUser/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NotificationUser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,Type")] tNotification tNotification)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tNotification);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tNotification);
        }

        // GET: NotificationUser/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.tNotifications == null)
            {
                return NotFound();
            }

            var tNotification = await _context.tNotifications.FindAsync(id);
            if (tNotification == null)
            {
                return NotFound();
            }
            return View(tNotification);
        }

        // POST: NotificationUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,Type")] tNotification tNotification)
        {
            if (id != tNotification.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tNotification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tNotificationExists(tNotification.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tNotification);
        }

        // GET: NotificationUser/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.tNotifications == null)
            {
                return NotFound();
            }

            var tNotification = await _context.tNotifications
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tNotification == null)
            {
                return NotFound();
            }

            return View(tNotification);
        }

        // POST: NotificationUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.tNotifications == null)
            {
                return Problem("Entity set 'ApplicationDbContext.tNotifications'  is null.");
            }
            var tNotification = await _context.tNotifications.FindAsync(id);
            if (tNotification != null)
            {
                _context.tNotifications.Remove(tNotification);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool tNotificationExists(int id)
        {
          return (_context.tNotifications?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

1640WebApp/Views/NotificationUser/Create.cshtml
@model _1640WebApp.Models.tNotification

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>tNotification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

1640WebApp/Views/NotificationUser/Delete.cshtml
@model _1640WebApp.Models.tNotification

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tNotification</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

1640WebApp/Views/NotificationUser/Details.cshtml
@model _1640WebApp.Models.tNotification

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>tNotification</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

1640WebApp/Views/NotificationUser/Edit.cshtml
@model _1640WebApp.Models.tNotification

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>tNotification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

1640WebApp/Views/NotificationUser/Index.cshtml
@model IEnumerable<_1640WebApp.Models.tNotification>

@{
    ViewData["Title"] = "Notificaton";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div style="padding: 42px">
    <div class="card ">
        <div class="card-header p-3">
            <div class="row">
                <div class="col-md-10 text-start">
                    <div class="row">
                        <h2 class="mb-0 col-md-2 text-start">@ViewBag.Title</h2>
                        <form method="get" action="@Url.Action("Search", "NotificationUser")" class="form-inline col-md-10 text-center">

                            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                                <div class="input-group input-group-outline">
                                    <input type="text" placeholder="search here" class="form-control" name="searchString" class="form-control mr-sm-2">
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="col-md-2 text-end">
                    <div class="form-group border text-center border-info rounded p-0 ">
                        @Html.DropDownList("Types", (IEnumerable<SelectListItem>)ViewBag.Types, new { @class = "form-control", @id = "filter-notification" })
                    </div>
                </div>
            </div>
        </div>
        <table class="card-body p-3">
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="padding: 12px 24px">
                            <div class="border border-info px-4 rounded">
                                <div class="row-lg-8 row-md-10 mx-auto ">
                                    <div class="row mt-4 border-bottom">
                                        <div class="col-md-10 text-start">
                                            <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
                                        </div>
                                        <div class="col-md-2 text-center">
                                            @switch (item.Type)
                                            {
                                                case "Danger":
                                                    <div class="bg-danger text-white border rounded-pill p-2">
                                                        @Html.DisplayFor(modelItem => item.Type)
                                                    </div>
                                                    break;
                                                case "Waring":
                                                    <div class="bg-warning text-white border rounded-pill p-2">
                                                        @Html.DisplayFor(modelItem => item.Type)
                                                    </div>
                                                    break;
                                                case "Info":
                                                    <div class="bg-info text-white border rounded-pill p-2">
                                                        @Html.DisplayFor(modelItem => item.Type)
                                                    </div>
                                                    break;

                                            }
                                        </div>
                                    </div>
                                    <div class="row m-4" style="position: relative;">
                                        <div class="col-md-10 text-start text-black">
                                            <div style="white-space: pre-line">@Html.DisplayFor(modelItem => item.Content)</div>
                                        </div>
                                        <div class="col-md-2 text-end text-black" style="position: absolute; bottom: 0; right: 0;">
                                            <a asp-action="Details" asp-route-id="@item.Id" class="border border-info px-4 rounded">Details</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!--   Core JS Files   -->
<script src="~/managerassets/js/core/popper.min.js"></script>
<script src="~/managerassets/js/core/bootstrap.min.js"></script>

@*script để lọc khi user chọn type sẽ trả về kết quả mà không cần nhấn submit *@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#filter-notification').change(function () {
            // lấy giá trị được chọn trong dropdown list
            //var type = $('#filter-notification').val();
            var type = $(this).val();
            // truyền gía trị user đã chọn vào controler bằng đường link
            // controller sẽ nhận và sử lý data
            //window.location.href = "/NotificationUser/Filter?type=" + type;
            window.location.href = '@Url.Action("Filter", "NotificationUser")?typeData=' + type;
        });
    });
</script>

<script src="~/managerassets/js/material-dashboard.min.js?v=3.0.4"></script>