1640WebApp/Controllers/DonationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _1640WebApp.Data;

namespace _1640WebApp.Controllers
{
    public class DonationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DonationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Donations
        public async Task<IActionResult> Index()
        {
              return View(await _context.Donations.ToListAsync());
        } 


        // GET: Donations/AddOrEdit
        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Donation());
            else
                return View(_context.Donations.Find(id));
        }

        // POST: Donations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> AddOrEdit([Bind("DonateID,AcccountNumber,BeneficaryName,BankName,SWIFTCode,Amount,DateTime")] Donation donation)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (donation.DonateID == 0)
        //        {
        //            donation.DateTime= DateTime.Now;
        //            _context.Add(donation);
        //        }
        //        else
        //            _context.Update(donation);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(donation);
        //}


        // POST: Donations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var donation = await _context.Donations.FindAsync(id);
            _context.Donations.Remove(donation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Donation donation)
        {
            if (ModelState.IsValid)
            {
                _context.Donations.Add(donation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(donation);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var donation = _context.Donations.FirstOrDefault(d => d.DonateID == id);
            if (donation == null)
            {
                return NotFound();
            }

            return View(donation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Edit(int id, [Bind("DonateID,AcccountNumber,BeneficaryName,BankName,SWIFTCode,Amount,DateTime")] Donation donation)
        {
            if (id != donation.DonateID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(donation);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DonationExists(donation.DonateID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(donation);
        }

        private bool DonationExists(int id)
        {
            return _context.Donations.Any(e => e.DonateID == id);
        }
    }
}

1640WebApp/Controllers/FundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _1640WebApp.Data;

namespace _1640WebApp.Controllers
{
    public class FundsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FundsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Funds
        public async Task<IActionResult> Index()
        {
              return _context.Funds != null ? 
                          View(await _context.Funds.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Funds'  is null.");
        }

        // GET: Funds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Funds == null)
            {
                return NotFound();
            }

            var funds = await _context.Funds
                .FirstOrDefaultAsync(m => m.Id == id);
            if (funds == null)
            {
                return NotFound();
            }

            return View(funds);
        }

        // GET: Funds/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Funds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NameFund,Content,Datetime")] Funds funds)
        {
            if (ModelState.IsValid)
            {
                _context.Add(funds);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(funds);
        }

        // GET: Funds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Funds == null)
            {
                return NotFound();
            }

            var funds = await _context.Funds.FindAsync(id);
            if (funds == null)
            {
                return NotFound();
            }
            return View(funds);
        }

        // POST: Funds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameFund,Content,Datetime")] Funds funds)
        {
            if (id != funds.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(funds);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FundsExists(funds.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(funds);
        }

        // GET: Funds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Funds == null)
            {
                return NotFound();
            }

            var funds = await _context.Funds
                .FirstOrDefaultAsync(m => m.Id == id);
            if (funds == null)
            {
                return NotFound();
            }

            return View(funds);
        }

        // POST: Funds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Funds == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Funds'  is null.");
            }
            var funds = await _context.Funds.FindAsync(id);
            if (funds != null)
            {
                _context.Funds.Remove(funds);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FundsExists(int id)
        {
          return (_context.Funds?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

1640WebApp/Views/Funds/Details.cshtml
@model _1640WebApp.Data.Funds

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Funds</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameFund)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameFund)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datetime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datetime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

1640WebApp/Views/Funds/Edit.cshtml
@model _1640WebApp.Data.Funds

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Funds</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NameFund" class="control-label"></label>
                <input asp-for="NameFund" class="form-control" />
                <span asp-validation-for="NameFund" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datetime" class="control-label"></label>
                <input asp-for="Datetime" class="form-control" />
                <span asp-validation-for="Datetime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

1640WebApp/Views/Funds/Index.cshtml
@model IEnumerable<_1640WebApp.Data.Funds>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="Donations" asp-action="Index">All View Donor</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NameFund)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Datetime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameFund)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Datetime)
            </td>
            <td>
                <a asp-controller="Donations" asp-action="Create" asp-route-id="@item.Id">AddDonation</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            </td>
        </tr>
}
    </tbody>
</table>