1640WebApp/Controllers/CatogoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using _1640WebApp.Data;
using Microsoft.EntityFrameworkCore;



namespace _1640WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CatogoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CatogoryController(ApplicationDbContext context)
        {
            _context = context;
        }
        private bool CatogoryExists(int id)
        {
            return _context.Catogorys.Any(e => e.Id == id);
        }

        public IActionResult Index()
        {
            var catogorys = _context.Catogorys.ToList();
            return View(catogorys);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Catogory catogory)
        {
            if (ModelState.IsValid)
            {
                _context.Catogorys.Add(catogory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(catogory);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var catogory = _context.Catogorys.FirstOrDefault(d => d.Id == id);
            if (catogory == null)
            {
                return NotFound();
            }

            return View(catogory);
        }

        [HttpPost]
        public IActionResult Edit(int id, [Bind("Id,Name")] Catogory catogory)
        {
            if (id != catogory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(catogory);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CatogoryExists(catogory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(catogory);
        }

       
        public async Task<IActionResult> Delete(int id)
        {
            var catogory = await _context.Catogorys.FindAsync(id);
            if (catogory == null)
            {
                return NotFound();
            }

            _context.Catogorys.Remove(catogory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

1640WebApp/Controllers/EmailController.cs
using _1640WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;
using _1640WebApp.Data;
using Microsoft.AspNetCore.Authorization;


namespace _1640WebApp.Controllers
{
    [Authorize(Roles = "Manager")]
    public class EmailController : Controller
    {
        public IActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Form(Email model)
        {
            using(MailMessage message = new MailMessage(model.From, model.To))
            {
                message.Subject = model.Subject;
                message.Body = model.Body;
                message.IsBodyHtml = false;
                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    NetworkCredential NetCre = new NetworkCredential(model.From, model.Password);
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = NetCre;
                    smtp.Port = 587;
                    smtp.Send(message);
                    ViewBag.Message = "Email Sent Successfully";

                }
                
                return View();
            }
        }
        
    }
}

1640WebApp/Controllers/IdeaController.cs
using _1640WebApp.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Text;
using Microsoft.Extensions.Caching.Memory;
using System.Net;
using System.Net.Mail;
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Threading.Tasks;


namespace _1640WebApp.Controllers
{
    [Authorize(Roles = "Staff, Admin, Manager, Coordinator")]
    
    
    public class IdeaController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IWebHostEnvironment _env;
        private readonly IMemoryCache _memoryCache;
        //private readonly ISendGridClient _sendGridClient;
        //private readonly IConfiguration _configuration;


        public IdeaController(IMemoryCache memoryCache, IHttpContextAccessor httpContextAccessor, IWebHostEnvironment env, ApplicationDbContext context = null, UserManager<ApplicationUser> userManager = null)
        {
            _context = context;
            _userManager = userManager;
            _env = env;
            _httpContextAccessor = httpContextAccessor;
            _memoryCache = memoryCache;
        }

        // GET: Ideas
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var ideas = await _context.Ideas
                            .Include(i => i.Catogories)
                            .Include(i => i.Submission)
                            .Include(i => i.User)
                            .OrderByDescending(i => i.Id)
                            .Skip((pageNumber - 1) * pageSize)
                            .Take(pageSize)
                            .ToListAsync();

            var count = await _context.Ideas.CountAsync();
            var totalPages = (int)Math.Ceiling(count / (double)pageSize);

            var Catogories = await _context.Catogorys.ToListAsync();
            var Submissions = await _context.Submissions.Select(i => i.Id).Distinct().ToListAsync();
            var latestDay = _context.Ideas.Max(n => n.Datatime);
            var earliestDay = _context.Ideas.Min(n => n.Datatime);

            var allOptions = new List<SelectListItem>();
            allOptions.Add(new SelectListItem { Text = " -- Select --", Value = "" });
            foreach (var Catogory in Catogories)
            {
                allOptions.Add(new SelectListItem { Text = Catogory.Name, Value = "category=" + Catogory.Id.ToString() });
            }
            foreach (var Submission in Submissions)
            {
                allOptions.Add(new SelectListItem { Text = $"Submission Id: " + Submission, Value = "submission=" + Submission.ToString() });
            }
            ViewBag.SelectList = allOptions;
            ViewBag.Cate = Catogories;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = pageNumber;

            return View(ideas);
        }
        //ton
        //sort in admin/manager page
        public async Task<IActionResult> FilterAdmin(string typeData)
        {
            var filterTxt = typeData.Split('=')[0];

            var ideas = await _context.Ideas
                            .Include(i => i.Catogories)
                            .Include(i => i.Submission)
                            .Include(i => i.User)
                            .OrderByDescending(i => i.Id)
                            .ToListAsync();

            // Distinct() lọc kết quả trùng
            var Catogories = await _context.Catogorys.ToListAsync();
            var Submissions = await _context.Submissions.Select(i => i.Id).Distinct().ToListAsync();
            var latestDay = _context.Ideas.Max(n => n.Datatime);
            var earliestDay = _context.Ideas.Min(n => n.Datatime);

            var allOptions = new List<SelectListItem>();
            allOptions.Add(new SelectListItem { Text = " -- Select --", Value = "" });
            foreach (var Catogory in Catogories)
            {
                allOptions.Add(new SelectListItem { Text = Catogory.Name, Value = "category=" + Catogory.Id.ToString() });
            }
            foreach (var Submission in Submissions)
            {
                allOptions.Add(new SelectListItem { Text = $"Submission Id: " + Submission, Value = "submission=" + Submission.ToString() });
            }
            ViewBag.SelectList = allOptions;

            if (!String.IsNullOrEmpty(typeData))
            {
                var filter =int.Parse(typeData.Split('=')[1]);
                if (filterTxt == "category")
                {
                    ideas = await _context.Ideas
                                .Include(i => i.Catogories)
                                .Include(i => i.Submission)
                                .Include(i => i.User)
                                .Where(i => i.CatogoryId == filter)
                                .OrderByDescending(i => i.Id)                             
                                .ToListAsync();
                }
                if (filterTxt == "submission")
                {
                    ideas = await _context.Ideas
                                .Include(i => i.Catogories)
                                .Include(i => i.Submission)
                                .Include(i => i.User)
                                .Where(i => i.SubmissionId == filter)
                                .OrderByDescending(i => i.Id)
                                .ToListAsync();
                }
                var count = ideas.Count();                
                ViewBag.Cate = Catogories;
            }
            return View("Index", ideas);
        }

        //ton
        // search in admin/manager page
        public async Task<IActionResult> SearchAdmin(string searchString)
        {
            var ideas = await _context.Ideas
                            .Include(i => i.Catogories)
                            .Include(i => i.Submission)
                            .Include(i => i.User)
                            .OrderByDescending(i => i.Id)
                            .ToListAsync();
            // Distinct() lọc kết quả trùng
            var Catogories = await _context.Catogorys.ToListAsync();
            var Submissions = await _context.Submissions.Select(i => i.Id).Distinct().ToListAsync();
            var latestDay = _context.Ideas.Max(n => n.Datatime);
            var earliestDay = _context.Ideas.Min(n => n.Datatime);

            var allOptions = new List<SelectListItem>();
            allOptions.Add(new SelectListItem { Text = " -- Select --", Value = "" });
            foreach (var Catogory in Catogories)
            {
                allOptions.Add(new SelectListItem { Text = Catogory.Name, Value = "category=" + Catogory.Id.ToString() });
            }
            foreach (var Submission in Submissions)
            {
                allOptions.Add(new SelectListItem { Text = $"Submission Id: " + Submission, Value = "submission=" + Submission.ToString() });
            }
            ViewBag.SelectList = allOptions;


            if (string.IsNullOrEmpty(searchString))
            {
                return RedirectToAction(nameof(Index));
            }

            // data after search
            // .Contains() search gần giống
            var results = await _context.Ideas
                        .Include(i => i.Catogories)
                        .Include(i => i.Submission)
                        .Include(i => i.User)
                        .Where(n => n.Title.Contains(searchString) ||
                                    n.Text.Contains(searchString))
                        .OrderByDescending(n => n.Id)
                        .ToListAsync();
            var count = results.Count();

            return View("Index", results);
        }

        private int getCurrentUserDepartmentId()
        {
            // Get the current user's ID
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get the current user's department ID
            ApplicationUser user = _context.Users.FirstOrDefault(u => u.Id == userId);
            int departmentId = user.DepartmentId;


            return departmentId;
        }

        // GET: ViewIdeas
        [HttpGet]
        [Route("ViewIdeas")]
        public async Task<IActionResult> ViewIdeas()
        {
            var user = await _userManager.GetUserAsync(User);
            var userImage = user.Image;
            var userName = user.Fullname_;
            var userEmail = user.Email;
            ViewBag.UserImage = userImage;
            ViewBag.UserName = userName;
            ViewBag.UserEmail = userEmail;

            //ton
            var newest = _context.Ideas.Max(n => n.Datatime);
            var oldest = _context.Ideas.Max(n => n.Datatime);

            var allOptions = new List<SelectListItem>();
            allOptions.Add(new SelectListItem { Text = " -- Select --", Value = "" });
            allOptions.Add(new SelectListItem { Text = "Newest", Value = "newest" });
            allOptions.Add(new SelectListItem { Text = "Oldest", Value = "oldest" });
            allOptions.Add(new SelectListItem { Text = "Most popular", Value = "MostPopular" });
            allOptions.Add(new SelectListItem { Text = "Least popular", Value = "LeastPopular" });

            ViewBag.SelectList = allOptions;

            var applicationDbContext = await _context.Ideas
                                            .Include(i => i.Submission)
                                            .Include(i => i.Reacts)
                                            .Include(i => i.User)

1640WebApp/Controllers/UserController.cs
using _1640WebApp.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace _1640WebApp.Controllers
{

    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public UserController(ApplicationDbContext context = null, UserManager<ApplicationUser> userManager = null)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            return View(users);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var departments = await _context.Departments.ToListAsync();
            if (user == null)
            {
                return NotFound();
            }
            var model = new ApplicationUser
            {
                StaffNumber = user.StaffNumber,
                Fullname_ = user.Fullname_,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                DepartmentId = user.DepartmentId,
                Departments = departments,
                
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ApplicationUser model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);
            var departments = await _context.Departments.ToListAsync();
            if (user == null)
            {
                return NotFound();
            }
            user.StaffNumber = model.StaffNumber;
            user.Fullname_ = model.Fullname_;
            user.Email = model.Email;
            user.PhoneNumber = model.PhoneNumber;
            user.DepartmentId = model.DepartmentId;
            var result = await _userManager.UpdateAsync(user);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "The error occured white updating the user");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var result = await _userManager.DeleteAsync(user);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "The error occured while deleting the user");
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
    
}

1640WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">v
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _1640WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_1640WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <script src="https://kit.fontawesome.com/b43c192976.js" crossorigin="anonymous"></script>
    
    <style>
        

        header{
            position: fixed;
            top: 0;
            right: 0;
            left: 0;
        }

        .footer {
            background-color: #24262b;
            padding: 70px 0;
            position: absolute;
            top: 100%;
            left: 0;
            right: 0;
        }

        .footer-col {
    width: 25%;
    padding: 0 15px;
}

    .footer-col h4 {
        font-size: 18px;
        color: #ffffff;
        text-transform: capitalize;
        margin-bottom: 35px;
        font-weight: 500;
        position: relative;
    }

        .footer-col h4::before {
            content: '';
            position: absolute;
            left: 0;
            bottom: -10px;
            background-color: #e91e63;
            height: 2px;
            box-sizing: border-box;
            width: 50px;
        }

    .footer-col ul li:not(:last-child) {
        margin-bottom: 10px;
    }

    .footer-col ul li a {
        font-size: 16px;
        text-transform: capitalize;
        color: #ffffff;
        text-decoration: none;
        font-weight: 300;
        color: #bbbbbb;
        display: block;
        transition: all 0.3s ease;
    }

        .footer-col ul li a:hover {
            color: #ffffff;
            padding-left: 8px;
        }

    .footer-col .social-links a {
        display: inline-block;
        height: 40px;
        width: 40px;
        background-color: rgba(255,255,255,0.2);
        margin: 0 10px 10px 0;
        text-align: center;
        line-height: 40px;
        border-radius: 50%;
        color: #ffffff;
        transition: all 0.5s ease;
    }

        .footer-col .social-links a:hover {
            color: #24262b;
            background-color: #ffffff;
        }


    </style>
</head>
<body class="body">
    <header style="z-index:1">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow " style="background-color: #24262b;">
            <div class="container-fluid">
                <button style="background-color: #fff;" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="display: flex; justify-content: center; align-items: center;">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="MainHome"> <img style="width: 30px;" src="~/images/logo.png" alt="Logo"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="MainHome">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Staff's rights
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Submission" asp-action="Index">Submission</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Idea" asp-action="ViewIdeas">View Ideas</a>
                                <a class="dropdown-item" asp-area="" asp-controller="NotificationUser" asp-action="Index">Notification</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Vote" asp-action="ViewVote">View Vote</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Manager's rights
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Email" asp-action="Form">Sent Email To Staff</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Analysis" asp-action="Index">Analysis</a>
                                <a class="dropdown-item" asp-area="" asp-controller="ManageFunds" asp-action="Index">Manage Funds</a>
                                <a class="dropdown-item" href="#">...</a>
                                <a class="dropdown-item" href="#">...</a>

                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Coordinator's rights
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="StaffManageByCoordinator" asp-action="Index">Manage Staff</a>
                                <a class="dropdown-item" asp-area="" asp-controller="StaffManageByCoordinator" asp-action="ViewSubmission">Submission</a>
                                <a class="dropdown-item" href="#">...</a>
                                <a class="dropdown-item" href="#">...</a>

                            </div>
                        </li>

                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin's rights
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="SubmissionManageByAdmin" asp-action="Index">Manage Submissions</a>
                                <a class="dropdown-item" asp-area="" asp-controller="StaffSubmissionManageByAdmin" asp-action="Index">Manage Staff's Submissions</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SuperUser" asp-action="Index">Roles</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                                <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Vote" asp-action="Index">Vote</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Catogory" asp-action="Index">Categorys</a>
                                <a class="dropdown-item" asp-area="" asp-controller="NotificationAdmin" asp-action="Index">Notificaitons</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Chat">Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="AboutUs">AboutUs</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>
    <div class="">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer style="text-align:left;" class="footer">
        <div style="background:#24262b;display:block;" class="container">
            <div class="row">
                <div class="footer-col">
                    <h4>company</h4>
                    <ul>
                        <li><a href="#">about us</a></li>
                        <li><a href="#">our services</a></li>
                        <li><a href="#">privacy policy</a></li>
                        <li><a href="#">affiliate program</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>get help</h4>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">shipping</a></li>
                        <li><a href="#">returns</a></li>
                        <li><a href="#">order status</a></li>
                        <li><a href="#">payment options</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>online shop</h4>
                    <ul>
                        <li><a href="#">watch</a></li>
                        <li><a href="#">bag</a></li>
                        <li><a href="#">shoes</a></li>
                        <li><a href="#">dress</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>follow us</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>